when:
  - event: push
  - event: pull_request

steps:
  - name: hello
    image: alpine:latest
    commands:
      - echo "Hello from test repo!"
      - echo "If baseline injection works, you should see security steps BEFORE this"
