when:
  - event: push
  - event: pull_request

steps:
  - name: hello
    image: alpine:latest@sha256:51183f2cfa6320055da30872f211093f9ff1d3cf06f39a0bdb212314c5dc7375
    commands:
      - echo "Hello from test repo!"
      - echo "If baseline injection works, you should see security steps BEFORE this"
